spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres1
    username: postgres
    password: cs@springfive
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql