spring:
    profiles:
      active: qa


    jpa:
      show-sql: true
      generate-ddl: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate.ddl-auto: create


#    mongodb:
#      database: cms
#      host: localhost
#      port: 27017
